### ISSUE TITLE
Allow installation from brew cask

### ISSUE THREAD

**Issue by klundberg** [athiercelin/Localizations#13]
Brew Cask is a great way to install release builds of apps like this one. I'd love to be able to manage this app that way.

https://caskroom.io

**Comment by e7711bbear** [comment]
I'm not familiar with it, I'll look into it and let you know!

**Comment by e7711bbear** [comment]
I've created the cask and submitted the PR to homebrew.
Thanks for the issue, I'm closing it now.

**Comment by klundberg** [comment]
Cool, thank you!

## 

Kevin Lundberg
